const canvas=document.querySelector('#world'),ctx=canvas.getContext('2d');
const speedLabel=document.querySelector('#speed'),missionLabel=document.querySelector('#mission'),locationLabel=document.querySelector('#location');
const style={avenue:{width:28,asphalt:'#454b4e',curb:'#989b96',edge:'#e7e0cf'},collector:{width:18,asphalt:'#53595a',curb:'#a9aaa3',edge:'#e9e2d4'},street:{width:10,asphalt:'#606565',curb:'#b7b7ad',edge:'#ece5d8'}};
const {nodes,roads:raw}=window.ALEY_ROADS,bounds={north:33.8148,south:33.8070,east:35.6105,west:35.5990},pad=26;
const P=(x,y)=>({x,y}),geo=([lat,lon])=>P(pad+(lon-bounds.west)/(bounds.east-bounds.west)*(canvas.width-pad*2),pad+(bounds.north-lat)/(bounds.north-bounds.south)*(canvas.height-pad*2));
const inside=([lat,lon])=>lat<bounds.north&&lat>bounds.south&&lon<bounds.east&&lon>bounds.west,kind={primary:'avenue',secondary:'avenue',tertiary:'collector',residential:'street',unclassified:'street',service:'street'};
const roads=raw.filter(r=>kind[r.t]&&r.p.some(id=>nodes[id]&&inside(nodes[id]))).map(r=>({type:r.t,kind:kind[r.t],points:r.p.map(id=>nodes[id]).filter(Boolean).map(geo)})).filter(r=>r.points.length>1);
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),close=(p,a,b)=>{let dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l)),x=a.x+dx*t,y=a.y+dy*t;return{x,y,d:Math.hypot(p.x-x,p.y-y)}};
function near(p){let best;roads.forEach(r=>r.points.slice(1).forEach((b,i)=>{let h=close(p,r.points[i],b);if(!best||h.d<best.d)best={...h,w:style[r.kind].width}}));return best}
function path(c,ps,w,col){c.beginPath();c.moveTo(ps[0].x,ps[0].y);for(let i=1;i<ps.length-1;i++){let p=ps[i],n=ps[i+1];c.quadraticCurveTo(p.x,p.y,(p.x+n.x)/2,(p.y+n.y)/2)}c.lineTo(ps.at(-1).x,ps.at(-1).y);c.lineWidth=w;c.lineCap='round';c.lineJoin='round';c.strokeStyle=col;c.stroke()}
const map=document.createElement('canvas');map.width=canvas.width;map.height=canvas.height;const m=map.getContext('2d');
function tree(x,y,r){m.fillStyle='#315f40';m.beginPath();m.arc(x,y,r,0,7);m.fill();m.fillStyle='#6d934e';m.beginPath();m.arc(x-r/4,y-r/4,r/2,0,7);m.fill()}
function render(){let g=m.createLinearGradient(0,0,canvas.width,canvas.height);g.addColorStop(0,'#e7dfcf');g.addColorStop(1,'#d4c5a9');m.fillStyle=g;m.fillRect(0,0,canvas.width,canvas.height);for(let x=60;x<canvas.width;x+=145)for(let y=85;y<canvas.height;y+=125){m.fillStyle=(x+y)%3?'#e3d5c0':'#d8c9b1';m.fillRect(x,y,70,42);m.strokeStyle='#b8ad99';m.strokeRect(x,y,70,42)}[[49,210],[91,274],[205,204],[365,128],[536,112],[708,140],[904,169],[1065,256],[1158,318],[987,455],[1128,508],[1080,690],[845,669],[610,670],[375,630],[175,543],[72,545],[276,730],[461,735]].forEach((p,i)=>tree(p[0],p[1],6+i%4));roads.forEach(r=>{let s=style[r.kind];path(m,r.points,s.width+8,s.edge)});roads.forEach(r=>{let s=style[r.kind];path(m,r.points,s.width+4,s.curb)});roads.forEach(r=>path(m,r.points,style[r.kind].width,style[r.kind].asphalt));let main=roads.find(r=>r.type==='primary');if(main){m.save();m.setLineDash([18,19]);path(m,main.points,1.6,'#f3db91');m.restore()}}
function length(r){return r.points.slice(1).reduce((n,p,i)=>n+dist(r.points[i],p),0)}function along(r,n){for(let i=1;i<r.points.length;i++){let a=r.points[i-1],b=r.points[i],l=dist(a,b);if(n<=l)return{x:a.x+(b.x-a.x)*n/l,y:a.y+(b.y-a.y)*n/l,a:Math.atan2(b.y-a.y,b.x-a.x)}n-=l}let a=r.points.at(-2),b=r.points.at(-1);return{x:b.x,y:b.y,a:Math.atan2(b.y-a.y,b.x-a.x)}}
const spawn=near(P(236,558)),car={x:spawn.x,y:spawn.y,a:-.39,v:0},keys=new Set(),traffic=[0,1,3,4,8].filter(i=>roads[i]).map((i,n)=>({r:roads[i],o:n*124,c:['#416b96','#d5a23d','#ba554d','#72846a','#765b91'][n]}));
function vehicle(x,y,a,c,s=1){ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillStyle=c;ctx.fillRect(-14*s,-8*s,28*s,16*s);ctx.fillStyle='#1e292b';ctx.fillRect(-5*s,-6*s,11*s,12*s);ctx.fillStyle='#ffe17d';ctx.fillRect(10*s,-4*s,4*s,8*s);ctx.strokeStyle='#fff7df';ctx.strokeRect(-14*s,-8*s,28*s,16*s);ctx.restore()}
let last=performance.now(),paused=document.hidden;function loop(now){if(paused)return;let dt=Math.min((now-last)/16.7,2);last=now;if(keys.has('w')||keys.has('arrowup'))car.v+=.075*dt;if(keys.has('s')||keys.has('arrowdown'))car.v-=.09*dt;car.v*=Math.pow(.94,dt);car.v=Math.max(-2.4,Math.min(4.1,car.v));let turn=(keys.has('a')||keys.has('arrowleft')?-1:0)+(keys.has('d')||keys.has('arrowright')?1:0);car.a+=turn*.046*dt*(car.v>=0?1:-1);let q=P(car.x+Math.cos(car.a)*car.v*dt,car.y+Math.sin(car.a)*car.v*dt),road=near(q);if(road.d<=road.w/2+9){car.x=q.x;car.y=q.y}else car.v*=.28;ctx.drawImage(map,0,0);traffic.forEach((t,i)=>{let p=along(t.r,(now*(.034+i*.004)+t.o)%length(t.r));vehicle(p.x,p.y,p.a,t.c,.72)});vehicle(car.x,car.y,car.a,'#dd3e37');speedLabel.textContent=Math.round(Math.abs(car.v)*19)+' km/h';missionLabel.textContent='Explore central Aley';locationLabel.textContent='Aley drive district';requestAnimationFrame(loop)}
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k)});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));document.addEventListener('visibilitychange',()=>{paused=document.hidden;if(!paused){last=performance.now();requestAnimationFrame(loop)}});render();requestAnimationFrame(loop);
